import { akte } from '@prisma/client';
import { type NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Oval } from 'react-loader-spinner';
import DropDown from '~/Components/Entry/Dropdown';
import Input from '~/Components/Entry/Input';
import ItemList from '~/Components/Entry/ItemList';
import Pagination from '~/Components/Entry/Pagination';
import Navbar from '~/Components/Navbar';
import { api } from '~/utils/api';

//TODO: get the filter data i want Akten? Aktenschrank?
const selectableItems = [
    { id: 1, name: 'Akten' },
    { id: 2, name: 'Aktenschrank' },
];

const Home: NextPage = () => {
    const [selected, setSelected] = useState(selectableItems[0]);
    const [filterName, setFilterName] = useState<string>('');
    const [filterResult, setFilterResult] = useState<akte[]>([]);
    const [splitData, setSplitData] = useState<akte[]>([]);
    const [pageNumber, setPageNumber] = useState<number>(1);
    const [pageLength, setPageLength] = useState<number>(1);

    const { data, refetch, isFetching, isSuccess } =
        api.fileManager.getAkten.useQuery({
            name: filterName ? filterName : undefined,
        });

    // filter and fetch data
    useEffect(() => {
        refetch();
        if (data && isSuccess) {
            setFilterResult(data);
        }
    }, [filterName, refetch, data, isSuccess]);

    // split data into pages
    useEffect(() => {
        const splitArray = (arr: akte[]) => {
            const result = [];
            for (let i = 0; i < arr.length; i += 8) {
                result.push(arr.slice(i, i + 8));
            }
            return result;
        };
        if (data && isSuccess) {
            setSplitData(splitArray(data)[pageNumber - 1]);
            setPageLength(splitArray(data).length);
        }
    }, [data, pageNumber, isSuccess, refetch]);

    return (
        <>
            <Head>
                <title>Flox File Picker</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="flex mt-2 w-screen justify-center gap-3">
                    <Input setFilterName={setFilterName} />
                    <DropDown
                        selectableItems={selectableItems}
                        setSelected={setSelected}
                        selected={selected}
                    />
                </div>
                <div className="px-96">
                    {isFetching && data === undefined ? (
                        <div className="absolute inset-0 bg-black/10">
                            <div className="relative left-1/2 top-1/2 z-50">
                                <Oval
                                    height={80}
                                    width={80}
                                    color="#4fa94d"
                                    wrapperStyle={{}}
                                    wrapperClass=""
                                    visible={true}
                                    ariaLabel="oval-loading"
                                    secondaryColor="#4fa94d"
                                    strokeWidth={2}
                                    strokeWidthSecondary={2}
                                />
                            </div>
                        </div>
                    ) : (
                        <div>
                            <ItemList pageLength={1} data={splitData} />
                            <Pagination setPageNumber={setPageNumber} pageLength={pageLength}
                            />
                        </div>
                    )}
                </div>
            </main>
        </>
    );
};

export default Home;
