
export const aktenMetadata = [
  {
    id: "1",
    name: "Aktenname 1",
    description: "Beschreibung 1",
    created: "2020-01-01",
    modified: "2020-01-01",
    status: "Status 1",
    type: "Typ 1",
    tags: ["Tag 1", "Tag 2"],
    owner: "Owner 1",
    creator: "Creator 1",
    company: "Company 1",
    location: "Location 1",
    department: "Department 1",
    category: "Category 1",
  },

  {
    id: "2",
    name: "Aktenname 2",
    description: "Beschreibung 2",
    created: "2020-02-02",
    modified: "2020-02-02",
    status: "Status 2",
    type: "Typ 2",
    tags: ["Tag 3", "Tag 4"],
    owner: "Owner 2",
    creator: "Creator 2",
    company: "Company 2",
    location: "Location 2",
    department: "Department 2",
    category: "Category 2",
  },
  {
    id: "3",
    name: "Aktenname 3",
    description: "Beschreibung 3",
    created: "2020-03-03",
    modified: "2020-03-03",
    status: "Status 3",
    type: "Typ 3",
    tags: ["Tag 5", "Tag 6"],
    owner: "Owner 3",
    creator: "Creator 3",
    company: "Company 3",
    location: "Location 3",
    department: "Department 3",
    category: "Category 3",
  },
  {
    id: "4",
    name: "Aktenname 4",
    description: "Beschreibung 4",
    created: "2020-04-04",
    modified: "2020-04-04",
    status: "Status 4",
    type: "Typ 4",
    tags: ["Tag 7", "Tag 8"],
    owner: "Owner 4",
    creator: "Creator 4",
    company: "Company 4",
    location: "Location 4",
    department: "Department 4",
    category: "Category 4",
  },
  {
    id: "5",
    name: "Aktenname 5",
    description: "Beschreibung 5",
    created: "2020-05-05",
    modified: "2020-05-05",
    status: "Status 5",
    type: "Typ 5",
    tags: ["Tag 9", "Tag 10"],
    owner: "Owner 5",
    creator: "Creator 5",
    company: "Company 5",
    location: "Location 5",
    department: "Department 5",
    category: "Category 5",
  },
  {
    id: "6",
    name: "Aktenname 6",
    description: "Beschreibung 6",
    created: "2020-06-06",
    modified: "2020-06-06",
    status: "Status 6",
    type: "Typ 6",
    tags: ["Tag 11", "Tag 12"],
    owner: "Owner 6",
    creator: "Creator 6",
    company: "Company 6",
    location: "Location 6",
    department: "Department 6",
    category: "Category 6",
  },
  {
    id: "7",
    name: "Aktenname 7",
    description: "Beschreibung 7",
    created: "2020-07-07",
    modified: "2020-07-07",
    status: "Status 7",
    type: "Typ 7",
    tags: ["Tag 13", "Tag 14"],
    owner: "Owner 7",
    creator: "Creator 7",
    company: "Company 7",
    location: "Location 7",
    department: "Department 7",
    category: "Category 7",
  },
  {
    id: "8",
    name: "Aktenname 8",
    description: "Beschreibung 8",
    created: "2020-08-08",
    modified: "2020-08-08",
    status: "Status 8",
    type: "Typ 8",
    tags: ["Tag 15", "Tag 16"],
    owner: "Owner 8",
    creator: "Creator 8",
    company: "Company 8",
    location: "Location 8",
    department: "Department 8",
    category: "Category 8",
  },
  {
    id: "9",
    name: "Aktenname 9",
    description: "Beschreibung 9",
    created: "2020-09-09",
    modified: "2020-09-09",
    status: "Status 9",
    type: "Typ 9",
    tags: ["Tag 17", "Tag 18"],
    owner: "Owner 9",
    creator: "Creator 9",
    company: "Company 9",
    location: "Location 9",
    department: "Department 9",
    category: "Category 9",
  },
  {
    id: "10",
    name: "Aktenname 10",
    description: "Beschreibung 10",
    created: "2020-10-10",
    modified: "2020-10-10",
    status: "Status 10",
    type: "Typ 10",
    tags: ["Tag 19", "Tag 20"],
    owner: "Owner 10",
    creator: "Creator 10",
    company: "Company 10",
    location: "Location 10",
    department: "Department 10",
    category: "Category 10",
  },
  {
    id: "11",
    name: "Aktenname 11",
    description: "Beschreibung 11",
    created: "2020-11-11",
    modified: "2020-11-11",
    status: "Status 11",
    type: "Typ 11",
    tags: ["Tag 21", "Tag 22"],
    owner: "Owner 11",
    creator: "Creator 11",
    company: "Company 11",
    location: "Location 11",
    department: "Department 11",
    category: "Category 11",
  },
  {
    id: "12",
    name: "Aktenname 12",
    description: "Beschreibung 12",
    created: "2020-12-12",
    modified: "2020-12-12",
    status: "Status 12",
    type: "Typ 12",
    tags: ["Tag 23", "Tag 24"],
    owner: "Owner 12",
    creator: "Creator 12",
    company: "Company 12",
    location: "Location 12",
    department: "Department 12",
    category: "Category 12",
  },
  {
    id: "13",
    name: "Aktenname 13",
    description: "Beschreibung 13",
    created: "2021-01-01",
    modified: "2021-01-01",
    status: "Status 13",
    type: "Typ 13",
    tags: ["Tag 25", "Tag 26"],
    owner: "Owner 13",
    creator: "Creator 13",
    company: "Company 13",
    location: "Location 13",
    department: "Department 13",
    category: "Category 13",
  },
  {
    id: "14",
    name: "Aktenname 14",
    description: "Beschreibung 14",
    created: "2021-02-02",
    modified: "2021-02-02",
    status: "Status 14",
    type: "Typ 14",
    tags: ["Tag 27", "Tag 28"],
    owner: "Owner 14",
    creator: "Creator 14",
    company: "Company 14",
    location: "Location 14",
    department: "Department 14",
    category: "Category 14",
  },
  {
    id: "15",
    name: "Aktenname 15",
    description: "Beschreibung 15",
    created: "2021-03-03",
    modified: "2021-03-03",
    status: "Status 15",
    type: "Typ 15",
    tags: ["Tag 29", "Tag 30"],
    owner: "Owner 15",
    creator: "Creator 15",
    company: "Company 15",
    location: "Location 15",
    department: "Department 15",
    category: "Category 15",
  },
];
export type dataview = typeof aktenMetadata;
